site:
    title: Payara Cloud Documentation
    start_page: docs::Overview.adoc
content:
    sources:
    - url: ./
      start_path: docs
      branches: HEAD
asciidoc:
    attributes:
        attribute-missing: 'skip'
ui:
    bundle:
        url: ./ui-bundle.zip
        snapshot: true
runtime:
    fetch: true
output:
    dir: ./build/html
